## Bài 2: Nguyên lý tiến hóa

### Cài đặt chương trình với các bước sau:
Khởi tạo quẩn thể nhị phân: quẩn thể gồm 6 cá thể, mỗi cá thể độ dài là 7

Tính fitness: fitness là số bit 1 trong cá thể

Chọn lọc: Tournament selection (chọn 2 cá thể ngẫu nhiên, giữ cá thể có 
fitness cao hơn). Thực hiện chọn 3 lần.

Lai ghép: Chọn 2 cá thể cha và thực hiện 1-point crossover tại vị trí ngẫu nhiên.

Đột biến: Lật ngẫu nhiên 1 bit trong cá thể con.


In [1]:
import numpy as np

In [20]:
def initialize_pop(pop_size=6, len_pop=7):
    return np.random.choice([0, 1], (pop_size, len_pop))

def fitness(pop):
    return np.sum(pop)


def tournament_selection(pops, num_selections=3):
    winners = []
    for _ in range(num_selections):
        idxs = np.random.choice(len(pops), 2, replace=False)
        ind1, ind2 = pops[idxs[0]], pops[idxs[1]]
        winner = ind1 if fitness(ind1) >= fitness(ind2) else ind2
        winners.append(winner.copy())
    return winners


def mutate(ind):
    idx = np.random.randint(len(ind))
    ind[idx] = 1 - ind[idx]
    return ind

def crossover(par1, par2):
    point = np.random.randint(1, len(par1))
    child1 = np.concatenate([par1[:point], par2[point:]])
    child2 = np.concatenate([par2[:point], par1[point:]])
    return child1, child2, point

In [21]:
np.random.seed(42)
pops = initialize_pop()
print("Quần thể ban đầu:")
for ind in pops:
    print(ind, "Fitness:", fitness(ind))

winners = tournament_selection(pops, num_selections=3)
print("\nCác cá thể được chọn (winners):")
for w in winners:
    print(w, "Fitness:", fitness(w))
idxs = np.random.choice(len(winners), 2, replace=False)
par1, par2 = winners[idxs[0]], winners[idxs[1]]
child1, child2, pos = crossover(par1, par2)
print(f"\nLai ghép tại vị trí {pos}:")
print("Cha 1:", par1)
print("Cha 2:", par2)
print("Con 1:", child1)
print("Con 2:", child2)
print("\nCác cá thể con được sinh ra:")
print(child1, "Fitness:", fitness(child1))
print(child2, "Fitness:", fitness(child2))

mutated1 = mutate(child1.copy())
mutated2 = mutate(child2.copy())
print("\nCác cá thể con sau khi đột biến:")
print(mutated1, "Fitness:", fitness(mutated1))
print(mutated2, "Fitness:", fitness(mutated2))

Quần thể ban đầu:
[0 1 0 0 0 1 0] Fitness: 2
[0 0 1 0 0 0 0] Fitness: 1
[1 0 1 1 1 0 1] Fitness: 5
[0 1 1 1 1 1 1] Fitness: 6
[1 1 0 0 1 1 1] Fitness: 5
[0 1 0 0 0 0 0] Fitness: 1

Các cá thể được chọn (winners):
[0 1 0 0 0 1 0] Fitness: 2
[0 1 0 0 0 1 0] Fitness: 2
[0 1 1 1 1 1 1] Fitness: 6

Lai ghép tại vị trí 2:
Cha 1: [0 1 0 0 0 1 0]
Cha 2: [0 1 1 1 1 1 1]
Con 1: [0 1 1 1 1 1 1]
Con 2: [0 1 0 0 0 1 0]

Các cá thể con được sinh ra:
[0 1 1 1 1 1 1] Fitness: 6
[0 1 0 0 0 1 0] Fitness: 2

Các cá thể con sau khi đột biến:
[0 1 1 0 1 1 1] Fitness: 5
[1 1 0 0 0 1 0] Fitness: 3
